### ISSUE TITLE
Properties contained by other properties will be erroneously fired when `listen`ing

### ISSUE THREAD

**Issue by seiyria** [endel/delta-listener#4]
Suppose I have an entity with properties x, y, map, xp, level.

If I do:

    this.worldRoom.state.listen('players/:id/x', 'replace', locDirChange.bind(this, 'x'));

and then `xp` changes, it will still fire.

Looking at [this](https://github.com/endel/delta-listener/blob/master/src/DeltaContainer.ts#L58) it seems as though it creates a regex with `x` as the search, which will obviously fire for any property that contains an `x`.

**Comment by endel** [comment]
Thanks for reporting! Version `1.1.1` has the fix already :D
